version = 1
SPDX-PackageName = "hugo-theme-govanity (Vanity URLs for Go packages with Hugo)"
SPDX-PackageDownloadLocation = "https://github.com/foundata/hugo-theme-govanity"
SPDX-PackageSupplier = "foundata GmbH (https://foundata.com)"
SPDX-PackageComment = """
This project may include calls to Application Programming Interfaces
("API calls"), as well as their respective specifications and code that
allows software to communicate with other software. API calls to products
or services developed outside of this project are not licensed under the
licensing or usage terms that govern this project. Any use of such API
calls and related external products is subject to applicable additional
agreements with their respective provider and does not alter, expand or
supersede any terms of these additional agreements.
"""

[[annotations]]
path = "**"
precedence = "closest"
SPDX-FileCopyrightText = "foundata GmbH (https://foundata.com)"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "static/favicon.ico"
precedence = "closest"
SPDX-FileCopyrightText = "Renee French"
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Optimized version of https://go.dev/favicon.ico; See note about the Go Gopher mascot at https://go.dev/brand."

[[annotations]]
path = "assets/styles/pico.min.css"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (c) 2019-2025 Pico"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "https://picocss.com/; Downloaded from https://raw.githubusercontent.com/picocss/pico/refs/heads/main/css/pico.min.css"

[[annotations]]
path = "static/images/logo-go-gopher-network.svg"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (c) Egon Elbre, https://egonelbre.com/"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "Downloaded on 2025-08-31 from https://raw.githubusercontent.com/egonelbre/gophers/refs/heads/master/vector/projects/network.svg"
